#!MANAGED-CONFIG https://www.eton.club/api/v1/client/subscribe?token=c9abbacf46725cce74a14af253e8eacf interval=43200 strict=true
# Thanks @Hackl0us SS-Rule-Snippet

[General]
loglevel = notify
ipv6 = false
skip-proxy = localhost, *.local, injections.adguard.org, local.adguard.org, 0.0.0.0/8, 10.0.0.0/8, 17.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.0.0.0/24, 192.0.2.0/24, 192.168.0.0/16, 192.88.99.0/24, 198.18.0.0/15, 198.51.100.0/24, 203.0.113.0/24, 224.0.0.0/4, 240.0.0.0/4, 255.255.255.255/32
tls-provider = default
show-error-page-for-reject = true
dns-server = 223.6.6.6, 119.29.29.29, 119.28.28.28
test-timeout = 5
internet-test-url = http://bing.com
proxy-test-url = http://bing.com

[Panel]

# Surfboard 的服务器和策略组配置方式与 Surge 类似, 可以参考 Surge 的规则配置手册: https://manual.nssurge.com/

[Proxy]


[Proxy Group]
# > 外部节点
🚀 手动选择 = select, policy-path=订阅链接, update-interval=0, no-alert=0, hidden=0, include-all-proxies=0
# > 策略组
🆎 Adblock = select,🚀 手动选择, 🇭🇰 香港节点, 🇺🇲 美国节点, 🇸🇬 新加坡节点, 🇯🇵 日本节点, 🇨🇳 台湾节点
🌏 国外网站 = select, Reject, Direct, 🚀 手动选择
🅱️ Bilibili = select, Direct, 🇭🇰 香港节点, 🇨🇳 台湾节点, 🚀 手动选择 
Ⓜ️ 微软服务 = select,🚀 手动选择, Direct, 🇭🇰 香港节点, 🇺🇲 美国节点, 🇸🇬 新加坡节点, 🇯🇵 日本节点, 🇨🇳 台湾节点
🍟 谷歌服务 = select,🚀 手动选择, Direct, 🇭🇰 香港节点, 🇺🇲 美国节点, 🇸🇬 新加坡节点, 🇯🇵 日本节点, 🇨🇳 台湾节点
🗑️ 黑白名单 = select,🚀 手动选择, Direct, 🇭🇰 香港节点, 🇺🇲 美国节点, 🇸🇬 新加坡节点, 🇯🇵 日本节点, 🇨🇳 台湾节点
# > 外部节点
🇭🇰 香港节点 = fallback, policy-path=订阅链接, update-interval=0, policy-regex-filter=(🇭🇰)|(港)|(Hong)|(HK)
🇨🇳 台湾节点 = fallback, policy-path=订阅链接, update-interval=0, policy-regex-filter=(🇨🇳)|(台)|(Tai)|(TW)
🇺🇲 美国节点 = fallback, policy-path=订阅链接, update-interval=0, policy-regex-filter=(🇺🇸)|(美)|(States)|(US)
🇯🇵 日本节点 = fallback, policy-path=订阅链接, update-interval=0, policy-regex-filter=(🇯🇵)|(日)|(Japan)|(JP)
🇸🇬 新加坡节点 = fallback, policy-path=订阅链接, update-interval=0, policy-regex-filter=(🇸🇬)|(新)|(Singapore)|(SG)


[Rule]
# 自定义规则
## 您可以在此处插入自定义规则
DOMAIN-SUFFIX,tophub.today,DIRECT
DOMAIN-SUFFIX,netmarble.com,🌏 国外网站
DOMAIN-SUFFIX,worldflipper.jp,🌏 国外网站
DOMAIN-SUFFIX,naver.com,🌏 国外网站
DOMAIN-SUFFIX,smartmediarep.com,🌏 国外网站
DOMAIN-SUFFIX,technews.tw,🌏 国外网站
DOMAIN,www.eton.club,🌏 国外网站

# Adblock
RULE-SET,https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Advertising/Advertising.list，🆎 Adblock

# Google 服务
RULE-SET,https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Google/Google.list,🍟 谷歌服务

# 微软服务
RULE-SET,https://ghproxy.com/https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/StreamingMedia/StreamingSE.list,Ⓜ️ 微软服务

# 国内网站
RULE-SET,https://ghproxy.com/https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/StreamingMedia/StreamingSE.list,🅱️ Bilibili

# 国内网站
RULE-SET,https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/ChinaMax/ChinaMax_Resolve.list,Direct

## PROXY
DOMAIN-SUFFIX,https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script@master/rule/Surge/Proxy/Proxy_Resolve.list,🌏 国外网站

# LAN
DOMAIN-SUFFIX,local,DIRECT
IP-CIDR,127.0.0.0/8,DIRECT
IP-CIDR,172.16.0.0/12,DIRECT
IP-CIDR,192.168.0.0/16,DIRECT
IP-CIDR,10.0.0.0/8,DIRECT
IP-CIDR,17.0.0.0/8,DIRECT
IP-CIDR,100.64.0.0/10,DIRECT
IP-CIDR,224.0.0.0/4,DIRECT
IP-CIDR6,fe80::/10,DIRECT

# 剩余未匹配的国内网站
DOMAIN-SUFFIX,cn,DIRECT
DOMAIN-KEYWORD,-cn,DIRECT

# 最终规则
GEOIP,CN,DIRECT
FINAL,🗑️ 黑白名单