# 需使用0.20.19版本以上cfw
# 将proxy-providers里面链接中的“你的订阅链接”全部替换即可
#[2023.03.06]更新proxy-providers用法；
#[2023.03.29]更新proxy-providers 代码，适配读取本地文件；



mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090


dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  default-nameserver: 
    - 119.29.29.29
    - 223.5.5.5
    - 8.8.4.4
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter: 
    - '*.lan'
    - 'stun.*.*.*'
    - 'stun.*.*'
    - time.windows.com
    - time.nist.gov
    - time.apple.com
    - time.asia.apple.com
    - '*.ntp.org.cn'
    - '*.openwrt.pool.ntp.org'
    - time1.cloud.tencent.com
    - time.ustc.edu.cn
    - pool.ntp.org
    - ntp.ubuntu.com
    - ntp.aliyun.com
    - ntp1.aliyun.com
    - ntp2.aliyun.com
    - ntp3.aliyun.com
    - ntp4.aliyun.com
    - ntp5.aliyun.com
    - ntp6.aliyun.com
    - ntp7.aliyun.com
    - time1.aliyun.com
    - time2.aliyun.com
    - time3.aliyun.com
    - time4.aliyun.com
    - time5.aliyun.com
    - time6.aliyun.com
    - time7.aliyun.com
    - '*.time.edu.cn'
    - time1.apple.com
    - time2.apple.com
    - time3.apple.com
    - time4.apple.com
    - time5.apple.com
    - time6.apple.com
    - time7.apple.com
    - time1.google.com
    - time2.google.com
    - time3.google.com
    - time4.google.com
    - music.163.com
    - '*.music.163.com'
    - '*.126.net'
    - musicapi.taihe.com
    - music.taihe.com
    - songsearch.kugou.com
    - trackercdn.kugou.com
    - '*.kuwo.cn'
    - api-jooxtt.sanook.com
    - api.joox.com
    - joox.com
    - y.qq.com
    - '*.y.qq.com'
    - streamoc.music.tc.qq.com
    - mobileoc.music.tc.qq.com
    - isure.stream.qqmusic.qq.com
    - dl.stream.qqmusic.qq.com
    - aqqmusic.tc.qq.com
    - amobile.music.tc.qq.com
    - '*.xiami.com'
    - '*.music.migu.cn'
    - music.migu.cn
    - '*.msftconnecttest.com'
    - '*.msftncsi.com'
    - localhost.ptlogin2.qq.com
    - '*.*.*.srv.nintendo.net'
    - '*.*.stun.playstation.net'
    - 'xbox.*.*.microsoft.com'
    - '*.ipv6.microsoft.com'
    - '*.*.xboxlive.com'
    - speedtest.cros.wr.pvp.net
  nameserver:
    - https://223.6.6.6/dns-query
    - https://rubyfish.cn/dns-query
    - https://dns.pub/dns-query
  fallback: 
    - https://dns.rubyfish.cn/dns-query
    - https://public.dns.iij.jp/dns-query
    - tls://8.8.4.4'
  fallback-filter:  
    geoip: true
    ipcidr: 
      - 240.0.0.0/4
      - 0.0.0.0/32
      - 127.0.0.1/32


proxy-providers:
  ALL:
    type: http
    url: https://api.v1.mk/sub?target=clash&url=你的链接&emoji=true&list=true&udp=true
    # 可以使用任意类型的链接替换上面文字，多个链接使用英文符号的竖杠|隔开一起写上即可；也可以将Clash订阅链接替换掉整个引号""内的链接
    interval: 3600
    filter: 0.5x|1.0x|1.5x|2.0x
    # 根据订阅内中的节点梳理关键字，排除无效节点，如“剩余流量：***”
    path: ./proxy/all.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204 

  #香港节点   
  HK:
    type: file
    path: ./proxy/all.yaml
    filter: 港|HK|(?i)Hong
    health-check:
      enable: true
      interval: 120
      url: http://www.gstatic.com/generate_204
 #日本节点
  JP:
    type: file
    path: ./proxy/all.yaml
    filter: 日|东京|JP|(?i)Japan
    health-check:
      enable: true
      interval: 120
      url: http://www.gstatic.com/generate_204
 #美国节点
  US:
    type: file
    path: ./proxy/all.yaml
    filter: 美|US|(?i)States|American
    health-check:
      enable: true
      interval: 120
      url: http://www.gstatic.com/generate_204
 #台湾节点
  TW:
    type: file
    path: ./proxy/all.yaml
    filter: 台|湾|TW|(?i)Taiwan
    health-check:
      enable: true
      interval: 120
      url: http://www.gstatic.com/generate_204 
   
proxies:

            
proxy-groups:
  - name: 🚀 手动切换
    type: select
    use:
      - ALL
    proxies:
      - ✈️ 自动选择

  - name: 🎮 Game
    type: select
    use: 
      null
    url: "http://www.gstatic.com/generate_204"

    interval: 300
  - name: ✈️ 自动选择
    type: url-test
    use: 
      - ALL 
    url: "http://www.gstatic.com/generate_204"
    interval: 300
  
  - name: 🆎 Adblock
    type: select
    proxies:
      - REJECT
      - 🚀 手动切换

  - name: 🎨 Figma
    type: select
    proxies:
      - DIRECT
      - 🚀 手动切换
      - ✈️ 自动选择

  - name: 🍎 苹果服务
    type: select
    proxies:
      - DIRECT
      - 🚀 手动切换
      - ✈️ 自动选择

  - name: 🧩 谷歌服务
    type: select
    use: 
      - ALL

  - name: 🧩 微软服务
    type: select
    use: 
      - ALL
    proxies:
      - DIRECT
      
  - name: 🎬 哔哩哔哩
    type: select
    proxies:
      - DIRECT
      - 🚀 手动切换
      - ✈️ 自动选择

  - name: 🌏 国外网站
    type: select
    proxies:
      - 🚀 手动切换
      - ✈️ 自动选择

  - name: 🗑️ 黑白名单  
    type: select
    proxies:
      - DIRECT
      - 🚀 手动切换
      - ✈️ 自动选择 

#20.14版本clash已忽略path属性，自动生成固定位置
rule-providers:
  #需代理网址（自用)
  my_proxy:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/surfingcatt/surfingcat/main/Clash/rules/my_proxy.yaml
    path: ./ruleset/my_proxy.yaml
    interval: 86400

  ChinaMax_Classical:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/ChinaMax/ChinaMax_Classical.yaml
    path: ./ruleset/ChinaMax_Classical.yaml
    interval: 86400

  Proxy_Classical:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Proxy/Proxy_Classical.yaml
    path: ./ruleset/Proxy_Classical.yaml
    interval: 86400

  Google:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Google/Google.yaml
    path: ./ruleset/Google.yaml
    interval: 86400

  Apple:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Apple/Apple.yaml
    path: ./ruleset/Apple.yaml
    interval: 86400
  
  Steam:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Steam/Steam.yaml
    path: ./ruleset/Steam.yaml
    interval: 86400

  Bing:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Bing/Bing.yaml
    path: ./ruleset/Bing.yaml
    interval: 86400

  OneDrive:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/OneDrive/OneDrive.yaml
    path: ./ruleset/OneDrive.yaml
    interval: 86400

  BiliBili:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/BiliBili/BiliBili.yaml
    path: ./ruleset/BiliBili.yaml
    interval: 86400
    
rules:
  - RULE-SET,my_proxy,🚀 手动切换
  - DOMAIN-SUFFIX,figma.com,🎨 Figma
  - DOMAIN-KEYWORD,openai,🧩 微软服务
  - RULE-SET,Bing,🧩 微软服务
  - RULE-SET,Steam,🚀 手动切换
  - RULE-SET,OneDrive,🧩 微软服务
  - RULE-SET,Google,🧩 谷歌服务
  - RULE-SET,Apple,🍎 苹果服务
  - RULE-SET,BiliBili,🎬 哔哩哔哩
  - RULE-SET,Proxy_Classical,🌏 国外网站
  - RULE-SET,ChinaMax_Classical,DIRECT
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,🗑️ 黑白名单
