# Mihomo 配置
# 日期：2026-06-16
# 配置作者：https://github.com/Amnesiash
# 适用版本：所有使用 Clash Meta 核心的程序


# 策略组类型模板 - 定义不同的策略组基础配置
BaseUrltest: &BaseUrltest {type: url-test, interval: 300, tolerance: 50, timeout: 3000, max-failed-times: 3, lazy: true, url: 'https://cp.cloudflare.com/generate_204', hidden: true} 

# 策略组
proxy-groups:
  # 应用策略层 - Select手动选择，支持多场景应用优化，使用时默认，也可修改
  - name: 手动选择
    type: select
    include-all: true
    exclude-type: direct
    icon: https://github.com/Amnesiash/ladder_rules_script/raw/main/Gallery/vpnlogo/Meta.png

  - name: 代理加速
    type: select
    proxies: [自动选择, 香港, 台湾, 日本, 新加坡, 美国, 其他地区, 手动选择, 直连]
    icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/Global.png

  - name: AI
    type: select
    proxies: [自动选择, 香港, 台湾, 日本, 新加坡, 美国, 其他地区, 手动选择, 直连]
    icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/AI.png

  - name: Telegram
    type: select
    proxies: [自动选择, 香港, 台湾, 日本, 新加坡, 美国, 其他地区, 手动选择, 直连]
    icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/Telegram_X.png

  - name: 国际流媒体
    type: select
    proxies: [自动选择, 香港, 台湾, 日本, 新加坡, 美国, 其他地区, 手动选择, 直连]
    icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/Streaming!CN.png

  - name: 漏网之鱼
    type: select
    proxies: [直连, 自动选择, 香港, 台湾, 日本, 新加坡, 美国, 其他地区, 手动选择]
    icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/Final.png

  # 地理策略层 - 自动测速节点选择
  - name: 自动选择
    <<: *BaseUrltest
    include-all: true
    icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/Auto.png

  - name: 香港
    <<: *BaseUrltest
    include-all: true
    exclude-type: direct
    filter: "(?i)港|hk|hongkong|hong kong"
    icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/Hong_Kong.png

  - name: 台湾
    <<: *BaseUrltest
    include-all: true
    exclude-type: direct
    filter: "(?i)台|tw|taiwan"
    icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/Taiwan.png

  - name: 日本
    <<: *BaseUrltest
    include-all: true
    exclude-type: direct
    filter: "(?i)日|jp|japan"
    icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/Japan.png

  - name: 新加坡
    <<: *BaseUrltest
    include-all: true
    exclude-type: direct
    filter: "(?i)新|sg|singapore"
    icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/Singapore.png

  - name: 美国
    <<: *BaseUrltest
    include-all: true
    exclude-type: direct
    filter: "(?i)美|us|unitedstates|united states"
    icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/United_States.png

  - name: 其他地区
    <<: *BaseUrltest
    include-all: true
    exclude-type: direct
    filter: "(?i)^(?!.*(?:🇭🇰|🇯🇵|🇺🇸|🇸🇬|🇨🇳|港|hk|hongkong|台|tw|taiwan|日|jp|japan|新|sg|singapore|美|us|unitedstates)).*"
    icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/United_Nations.png

# ==================== 规则集 ====================
# 规则集行为模板
c: &RuleSet_c {type: http, behavior: classical, format: text, interval: 86400}

# 规则提供者
rule-providers:
  Direct:
    <<: *RuleSet_c
    url: https://github.com/Amnesiash/ladder_rules_script/raw/main/rules/release/Direct.list
    path: ./ruleset/Direct.list

  Private:
    <<: *RuleSet_c
    url: https://github.com/Amnesiash/ladder_rules_script/raw/main/rules/release/Private.list
    path: ./ruleset/Private.list

  AI:
    <<: *RuleSet_c
    url: https://github.com/Amnesiash/ladder_rules_script/raw/main/rules/release/AI.list
    path: ./ruleset/AI.list

  Telegram:
    <<: *RuleSet_c
    url: https://github.com/Amnesiash/ladder_rules_script/raw/main/rules/release/Telegram.list
    path: ./ruleset/Telegram.list

  Streaming:
    <<: *RuleSet_c
    url: https://github.com/Amnesiash/ladder_rules_script/raw/main/rules/release/Streaming.list
    path: ./ruleset/Streaming.list

  Proxy:
    <<: *RuleSet_c
    url: https://github.com/Amnesiash/ladder_rules_script/raw/main/rules/release/Proxy.list
    path: ./ruleset/Proxy.list

  China:
    <<: *RuleSet_c
    url: https://github.com/Amnesiash/ladder_rules_script/raw/main/rules/release/China.list
    path: ./ruleset/China.list

# 规则路由
rules:
  # > 订阅规则
  - RULE-SET, Private, 直连
  - RULE-SET, Direct, 直连
  - RULE-SET, AI, AI
  - RULE-SET, Telegram, Telegram
  - RULE-SET, Streaming, 国际流媒体
  - RULE-SET, Proxy, 代理加速
  - RULE-SET, China, 直连
  - GEOIP, CN, 直连

  # 兜底规则
  - MATCH, 漏网之鱼
