# Mihomo 覆写配置
# 日期：2026-09-07
# 配置作者：https://github.com/Amnesiash
# 适用版本：所有使用 Clash Meta 核心的程序


# ==================== 锚点配置 ====================
# 策略组类型模板 - 定义不同的策略组基础配置
auto:  &a2 {type: url-test, include-all: true, exclude-type: direct, interval: 900, lazy: true, url: 'http://www.gstatic.com/generate_204', hidden: false} 

# 规则集行为模板
c: &r1 {type: http, behavior: classical, format: text, interval: 86400}

# 策略组
proxy-groups:
  # 应用策略层 - Select手动选择，支持多场景应用优化，使用时默认，也可修改
  - name: 手动选择
    type: select
    include-all: true
    icon: https://github.com/Amnesiash/ladder_rules_script/raw/main/gallery/vpnlogo/Meta.png

  - name: 代理加速
    type: select
    proxies: [自动选择, 香港, 台湾, 日本, 新加坡, 美国, 手动选择, DIRECT]
    icon: https://github.com/Amnesiash/ladder_rules_script/raw/main/gallery/Orz-3/Color/Global.png

  - name: AI
    type: select
    proxies: [自动选择, 香港, 台湾, 日本, 新加坡, 美国, 手动选择, DIRECT]
    icon: https://github.com/Amnesiash/ladder_rules_script/raw/main/gallery/color/OpenAI.png

  - name: Telegram
    type: select
    proxies: [自动选择, 香港, 台湾, 日本, 新加坡, 美国, 手动选择, DIRECT]
    icon: https://github.com/Amnesiash/ladder_rules_script/raw/main/gallery/Orz-3/Color/Telegram.png

  - name: 国际流媒体
    type: select
    proxies: [自动选择, 香港, 台湾, 日本, 新加坡, 美国, 手动选择, DIRECT]
    icon: https://github.com/Amnesiash/ladder_rules_script/raw/main/gallery/Orz-3/Color/Streaming.png

  - name: 漏网之鱼
    type: select
    proxies: [DIRECT, 自动选择, 香港, 台湾, 日本, 新加坡, 美国, 手动选择]
    icon: https://github.com/Amnesiash/ladder_rules_script/raw/main/gallery/Orz-3/Color/Final.png

  # 地理策略层 - 自动测速节点选择
  - name: 自动选择
    <<: *a2
    icon: https://github.com/Amnesiash/ladder_rules_script/raw/main/gallery/Orz-3/Color/Auto.png

  - name: 香港
    <<: *a2
    filter: "(?i)港|hk|hongkong|hong kong"
    icon: https://github.com/Amnesiash/ladder_rules_script/raw/main/gallery/Orz-3/Color/HK.png

  - name: 台湾
    <<: *a2
    filter: "(?i)台|tw|taiwan"
    icon: https://github.com/Amnesiash/ladder_rules_script/raw/main/gallery/Orz-3/Color/TW.png

  - name: 日本
    <<: *a2
    filter: "(?i)日|jp|japan"
    icon: https://github.com/Amnesiash/ladder_rules_script/raw/main/gallery/Orz-3/Color/JP.png

  - name: 新加坡
    <<: *a2
    filter: "(?i)新|sg|singapore"
    icon: https://github.com/Amnesiash/ladder_rules_script/raw/main/gallery/Orz-3/Color/SG.png

  - name: 美国
    <<: *a2
    filter: "(?i)美|us|unitedstates|united states"
    icon: https://github.com/Amnesiash/ladder_rules_script/raw/main/gallery/Orz-3/Color/US.png

# 规则集
rule-providers:
  Direct:
    <<: *r1
    url: https://github.com/Amnesiash/ladder_rules_script/raw/main/rules/release/Direct.list
    path: ./ruleset/Direct.list

  Private:
    <<: *r1
    url: https://github.com/Amnesiash/ladder_rules_script/raw/main/rules/release/Private.list
    path: ./ruleset/Private.list

  AI:
    <<: *r1
    url: https://github.com/Amnesiash/ladder_rules_script/raw/main/rules/release/AI.list
    path: ./ruleset/AI.list

  Telegram:
    <<: *r1
    url: https://github.com/Amnesiash/ladder_rules_script/raw/main/rules/release/Extra/Telegram.list
    path: ./ruleset/Extra/Telegram.list

  Streaming:
    <<: *r1
    url: https://github.com/Amnesiash/ladder_rules_script/raw/main/rules/release/Streaming.list
    path: ./ruleset/Streaming.list

  SteamCN:
    <<: *r1
    url: https://github.com/Amnesiash/ladder_rules_script/raw/main/rules/release/Extra/SteamCN.list
    path: ./ruleset/Extra/SteamCN.list

  Proxy:
    <<: *r1
    url: https://github.com/Amnesiash/ladder_rules_script/raw/main/rules/release/Proxy.list
    path: ./ruleset/Proxy.list

  China:
    <<: *r1
    url: https://github.com/Amnesiash/ladder_rules_script/raw/main/rules/release/China.list
    path: ./ruleset/China.list

# 规则路由
rules:
  # > 订阅规则
  - RULE-SET, Private, DIRECT
  - RULE-SET, Direct, DIRECT
  - RULE-SET, AI, AI
  - RULE-SET, Telegram, Telegram
  - RULE-SET, Streaming, 国际流媒体
  - RULE-SET, SteamCN, DIRECT
  - RULE-SET, Proxy, 代理加速
  - RULE-SET, China, DIRECT
  - GEOIP, CN, DIRECT

  # 兜底规则
  - MATCH, 漏网之鱼
