# 2025-01-22

name: Fork & Edit Clash List Version

on:
  workflow_dispatch:
  schedule:
    # "早上12点与中午12点运行"
    - cron: "0 8,20 * * *"

jobs:
  Fork-FLITER-list:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Shanghai'
    
    steps: 
    - name: Checkout target repository
      uses: actions/checkout@v4.1.0
      with:
        repository: Amnesiash/ladder_rules_script
        path: ladder-repo

######  
    # 加载规则:Clash List 版本 🧸
    - name: Download Clash Rules List Version
      run: |
        mkdir -p ladder-repo/Rules/Clash/List Version
        
        # 直连修正
        curl -L -o ladder-repo/Rules/Clash/List Version/Direct+.list "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/UnBan.list"  

        # 代理列表
        curl -L -o ladder-repo/Rules/Clash/List Version/Proxy.list "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/ProxyGFWlist.list"

        # 直连列表
        curl -L -o ladder-repo/Rules/Clash/List Version/Direct.list "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/ChinaDomain.list"

        # LAN
        curl -L -o ladder-repo/Rules/Clash/List Version/LAN.list "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/LocalAreaNetwork.list"
        
        # 流媒体
        curl -L -o ladder-repo/Rules/Clash/List Version/Streaming!CN.list "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/ProxyMedia.list"
        curl -L -o ladder-repo/Rules/Clash/List Version/BilibiliHMT.list "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Ruleset/BilibiliHMT.list"

        # 苹果服务
        curl -L -o ladder-repo/Rules/Clash/List Version/Apple.list "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Apple.list"

        # GoogleCN
        curl -L -o ladder-repo/Rules/Clash/List Version/GoogleCN.list "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/GoogleCN.list" 
        
        # WeChat
        curl -L -o ladder-repo/Rules/Clash/List Version/WeChat.list "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Ruleset/Wechat.list"  

        # Telegram
        curl -L -o ladder-repo/Rules/Clash/List Version/Telegram.list "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Ruleset/Telegram.list"  

        # SteamCN
        curl -L -o ladder-repo/Rules/Clash/List Version/SteamCN.list "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Ruleset/SteamCN.list" 
        
        
######
    - name: Add 和 Commits
      run: |
        cd ladder-repo
        if [[ -n $(git status -s) ]]; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Auto Update $(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M')"
          git push origin HEAD
        else
          echo "No changes to commit."
        fi

    - name: Cleanup Workflow
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 2